apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "helm-operator-metrics.fullname" . }}
  labels:
    app: {{ template "helm-operator-metrics.name" . }}
    chart: {{ template "helm-operator-metrics.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "helm-operator-metrics.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.service.port | quote }}
        prometheus.io/path: "/metrics"
      labels:
        app: {{ template "helm-operator-metrics.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.podSecurityContext }}
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccountName }}
{{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.containerSecurityContext }}
          securityContext:
{{ toYaml .Values.containerSecurityContext | indent 12 }}
          {{- end }} 
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TELEMETRY_HOST
              value: {{ .Values.telemetry.host | quote }}
            - name: TELEMETRY_PORT
              value: {{ .Values.telemetry.port | quote }}
            - name: METRICS_NAMESPACE
              value: {{ .Values.metricsNamespace | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
            - name: VERSION
              value: {{ .Values.image.tag }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}