# Default values for helm-operator-metrics.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

serviceAccountName: helm-operator-metrics

logLevel: info
metricsNamespace: helmrelease

image:
  repository: stakater/helm-operator-metrics
  tag: 1.0.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

telemetry:
  host: 0.0.0.0
  port: 8080

# Healthness and readiness probes need relatively large timeouts because they query the kubernetes master
readinessProbe:
  timeoutSeconds: 5

livenessProbe:
  timeoutSeconds: 5

# Create ServiceMonitor custom resource required for Prometheus Operator to scrape the service
serviceMonitor:
  create: true
  interval: 10s
  scrapeTimeout: 10s
  # By default, Prometheus Operator uses its own Release label as the selector for ServiceMonitors.
  # Update this to match the release name of your Prometheus Operator installation if 
  # you aren't using custom match labels on your Prometheus definition.
  releaseLabel: prometheus-operator
  # Additional labels to add to the ServiceMonitor in case Prometheus Operator is configured with 
  # different matchLabels configuration, to make sure it matches this ServiceMonitor.
  # If this is defined, the release label of the service monitor will match kube-eagle's one
  additionalLabels: 
